version: "3.9"

services:
  mysql_database:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: django-app:v1
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "sh /app/scripts/entrypoint.sh"
    depends_on:
      - mysql_database

volumes:
  mysql_data:


