version: "3.9"
services:
  mysql_database:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: django-app:v1
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "sh /app/scripts/entrypoint.sh"
    depends_on:
      - mysql_database
volumes:
  mysql_data:
